// Auto-generated by lexer_generator.py
#include <stdio.h>
#include <token.h>
#include <math_tokens.h>
#include <tex_tokens.h>

char *line;
int pos;

Token get_next_token(void){
    cur_char = line[pos];

    if (is_blank(cur_char))
        return skip_blanks()

    if (isalpha(cur_char))
        return get_word()

    // Backslash tokens
    if (char == "\\")
        switch (next_char = self.line[self.pos]){
            case "\\":
                return new_m_newline_token();
            case ")":
                return new_m_stop_inl_math_token();
            case "]":
                return new_m_stop_dsp_math_token();
            case "{":
                return new_m_lset_brace_token();
            case "}":
                return new_m_rset_brace_token();
      }
    // Two character tokens
    if (cur_char == "$"){
        next_char = line[pos + 1];
        if (next_char == "$")
            return new_m_stop_dbl_dollar_token();
    }
    if (cur_char == "_"){
        next_char = line[pos + 1];
        if (next_char == "{")
            return new_m_lsub_grp_token();
    }
    if (cur_char == "^"){
        next_char = line[pos + 1];
        if (next_char == "{")
            return new_m_lsup_grp_token();
    }

    // Single character tokens
    switch(cur_char){   
        case "_"
            return new_m_sub_token();
        case "^"
            return new_m_sup_token();
        case "&"
            return new_m_align_token();
        case "("
            return new_m_lpar_token();
        case ")"
            return new_m_rpar_token();
        case "["
            return new_m_lsqb_token();
        case "]"
            return new_m_rsqb_token();
        case "{"
            return new_m_lbrace_token();
        case "}"
            return new_m_rbrace_token();
        case "$"
            return new_m_stop_dollar_token();
        case "}"
            return new_m_rsub_grp_token();
        case "}"
            return new_m_rsup_grp_token();
   }
}


