// Auto-generated by lexer_generator.py
#include <stdio.h>
#include <token.h>
#include <token_values.h>
#include "tex_lexer.h"
#include <tex_tokens.h>


Token get_next_token(char first_char, char second_char){
    char *curr_char;
    char *lookahead;
    strcpy(curr_char, first_char);
    strcpy(lookahead, second_char);

    if (is_blank(curr_char))
        return skip_blanks();

    if (isalpha(curr_char))
        return get_word();

    // Backslash tokens
    if (strcmp(curr_char, "\\"))
        switch (hash(lookahead)){
            case BACKLASH:
                return new_t_newline_token();
            case LPAR:
                return new_t_l_inl_math_token();
            case RPAR:
                return new_t_r_inl_math_token();
            case LSQB:
                return new_t_l_dsp_math_token();
            case RSQB:
                return new_t_r_dsp_math_token();
            case COMMA:
                return new_t_comma_skip_token();
            case COLON:
                return new_t_colon_skip_token();
            case SEMICOLON:
                return new_t_semic_skip_token();
            case EXCLM:
                return new_t_exclm_skip_token();
            case RANGLE:
                return new_t_rcart_skip_token();
       }
    // Two character tokens
    if (strcmp(curr_char, "$") && strcmp(lookahead, "$")
        return new_t_dbl_dollar_token();
    if (strcmp(curr_char, "`") && strcmp(lookahead, "`")
        return new_t_l_quote_token();
    if (strcmp(curr_char, "'") && strcmp(lookahead, "'")
        return new_t_r_quote_token();

    // Single character tokens
    switch(hash(curr_char)){   
        case LPAR:
            return new_t_lpar_token();
        case RPAR:
            return new_t_rpar_token();
        case LSQB:
            return new_t_lsqb_token();
        case RSQB:
            return new_t_rsqb_token();
        case LBRACE:
            return new_t_lbrace_token();
        case RBRACE:
            return new_t_rbrace_token();
        case DOLLAR:
            return new_t_dollar_token();
        case TILDE:
            return new_t_nobreak_token();
   }
}


