// Auto-generated by lexer_generator.py
#include <stdio.h>
#include <string.h>
#include "token.h"
#include "tex_tokens.h"

// * Change get_next_token to take in two characters.
// * Produce an error message for the default case of the backslash switch statement
// * We need to use strcmp via <string.h>
// * Change "cur_char" to "curr_char"
// * We cannot make a switch statement for strings. The token need to correspond to numbers, and we check
//   against those numbers. These numbers should be auto-generated.

Token get_next_token(char first_char, char second_char){
    strcpy(cur_char, first_char);
    strcpy(lookahead, second_char);

    if (is_blank(cur_char))
        return skip_blanks();

    if (isalpha(cur_char))
        return get_word();

    // Backslash tokens
    if (char == "\\")
        switch (lookahead){
            case "\\":
                return new_t_newline_token();
            case "(":
                return new_t_l_inl_math_token();
            case ")":
                return new_t_r_inl_math_token();
            case "[":
                return new_t_l_dsp_math_token();
            case "]":
                return new_t_r_dsp_math_token();
            case ",":
                return new_t_comma_skip_token();
            case ":":
                return new_t_colon_skip_token();
            case ";":
                return new_t_semic_skip_token();
            case "!":
                return new_t_exclm_skip_token();
            case ">":
                return new_t_rcart_skip_token();
            default:
                printf("Syntax Error: Unrecognized characters \\%c", lookahead);
      }
    // Two character tokens
    if (strcmp(cur_char, "$")){
        next_char = lookahead;
        if (strcmp(next_char == "$"))
            return new_t_dbl_dollar_token();
    }
    if (strcmp(cur_char, "`")){
        next_char = lookahead;
        if (strcmp(next_char == "`"))
            return new_t_l_quote_token();
    }
    if (strcmp(cur_char, "'")){
        next_char = lookahead;
        if (strcmp(next_char, "'"))
            return new_t_r_quote_token();
    }

    // Single character tokens
    switch(cur_char){   
        case "("
            return new_t_lpar_token();
        case ")"
            return new_t_rpar_token();
        case "["
            return new_t_lsqb_token();
        case "]"
            return new_t_rsqb_token();
        case "{"
            return new_t_lbrace_token();
        case "}"
            return new_t_rbrace_token();
        case "$"
            return new_t_dollar_token();
        case "~"
            return new_t_nobreak_token();
   }
}


