// Auto-generated by lexer_generator.py
#include <stdio.h>
#include <token.h>
#include <math_tokens.h>
#include <tex_tokens.h>

char *line;
int pos;

Token get_next_token(void){
    cur_char = line[pos];

    if (is_blank(cur_char))
        return skip_blanks()

    if (isalpha(cur_char))
        return get_word()

    // Backslash tokens
    if (char == "\\")
        switch (next_char = self.line[self.pos]){
            case "\\":
                return new_t_newline_token();
            case "(":
                return new_t_l_inl_math_token();
            case ")":
                return new_t_r_inl_math_token();
            case "[":
                return new_t_l_dsp_math_token();
            case "]":
                return new_t_r_dsp_math_token();
            case ",":
                return new_t_comma_skip_token();
            case ":":
                return new_t_colon_skip_token();
            case ";":
                return new_t_semic_skip_token();
            case "!":
                return new_t_exclm_skip_token();
            case ">":
                return new_t_rcart_skip_token();
      }
    // Two character tokens
    if (cur_char == "$"){
        next_char = line[pos + 1];
        if (next_char == "$")
            return new_t_dbl_dollar_token();
    }
    if (cur_char == "`"){
        next_char = line[pos + 1];
        if (next_char == "`")
            return new_t_l_quote_token();
    }
    if (cur_char == "'"){
        next_char = line[pos + 1];
        if (next_char == "'")
            return new_t_r_quote_token();
    }

    // Single character tokens
    switch(cur_char){   
        case "("
            return new_t_lpar_token();
        case ")"
            return new_t_rpar_token();
        case "["
            return new_t_lsqb_token();
        case "]"
            return new_t_rsqb_token();
        case "{"
            return new_t_lbrace_token();
        case "}"
            return new_t_rbrace_token();
        case "$"
            return new_t_dollar_token();
        case "~"
            return new_t_nobreak_token();
   }
}


