// Auto-generated from token_generator.py
#include "token.h"
Token new_word_token(void);
Token new_space_token(void);
Token new_comment_token(void);
Token new_eol_token(void);
Token new_escape_char_token(void);
Token new_eof_token(void);
Token new_lpar_token(void);
Token new_rpar_token(void);
Token new_lsqb_token(void);
Token new_rsqb_token(void);
Token new_lbrace_token(void);
Token new_backslash_token(void);
Token new_newline_token(void);
Token new_dollar_token(void);
Token new_dbl_dollar_token(void);
Token new_l_inl_math_token(void);
Token new_r_inl_math_token(void);
Token new_l_dsp_math_token(void);
Token new_r_dsp_math_token(void);
Token new_comma_skip_token(void);
Token new_colon_skip_token(void);
Token new_semic_skip_token(void);
Token new_exclm_skip_token(void);
Token new_rcart_skip_token(void);
Token new_nobreak_token(void);
Token new_l_quote_token(void);
Token new_r_quote_token(void);
